#define TAPPING_TERM 175
#define PLOOPY_DPI_OPTIONS { 400, 1600 }
#define PLOOPY_DPI_DEFAULT 1
#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_INVERT
#define PLOOPY_DRAGSCROLL_MULTIPLIER 0.1